[workflows] making sure the repo is not dirty after build/tests (#4)
* [workflows] making sure the repo is not dirty after build/tests

* replace with bash script in order to work on win/mac

* checking that ci check works

* Revert "checking that ci check works"

This reverts commit 089af0ab0ce4a774de306beeb33be374ccc8e0e3.

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -26,6 +26,16 @@ jobs:
       - name: Run tests
         run: cargo test --locked
 
+      - name: Check if there are changes
+        shell: bash
+        run: |
+          if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
+            echo "::error title=Repository modified by CI::Did you forget to commit rust.ungram?"
+            echo "Changes:"
+            git status --short
+            exit 1
+          fi
+
   format:
     runs-on: ubuntu-latest
     steps:
