replace with bash script in order to work on win/mac

diff --git a/.github/workflows/pr.yml b/.github/workflows/pr.yml
--- a/.github/workflows/pr.yml
+++ b/.github/workflows/pr.yml
@@ -26,9 +26,15 @@ jobs:
       - name: Run tests
         run: cargo test --locked
 
-      # Making sure that e.g. `rust.ungram` is updated and committed.
       - name: Check if there are changes
-        uses: NathanielHill/fail-if-changes@master
+        shell: bash
+        run: |
+          if [[ -n "$(git status --porcelain --untracked-files=no)" ]]; then
+            echo "::error title=Repository modified by CI::Did you forget to commit rust.ungram?"
+            echo "Changes:"
+            git status --short
+            exit 1
+          fi
 
   format:
     runs-on: ubuntu-latest
